// ============================================================
//  DATA.JS — Bộ từ vựng của bạn
//  Chỉnh sửa mảng này để thay đổi nội dung học.
//  Mỗi object gồm:
//    word    — từ tiếng Anh (sẽ là đáp án)
//    meaning — nghĩa tiếng Việt (sẽ hiển thị trên màn hình)
// ============================================================

const vocabularies = [
  { word: "ability", meaning: "capacity: khả năng | ability to + V (khả năng làm gì) | of all abilities (ở mọi trình độ)" },
  { word: "able", meaning: "capable: có thể, có khả năng | be able to + V (có thể làm gì)" },
  { word: "about to", meaning: "on the point of: sắp sửa | be about to + V (sắp làm gì)" },
  { word: "above all", meaning: "most importantly: trên hết, quan trọng nhất | dùng để nhấn mạnh ý chính" },
  { word: "abruptly", meaning: "suddenly: đột ngột | end abruptly (kết thúc đột ngột)" },
  { word: "absence", meaning: "lack, nonattendance: sự vắng mặt | absence of + N (sự thiếu vắng của...)" },
  { word: "accept", meaning: "receive: chấp nhận | accept an award / payment / position (nhận giải thưởng / tiền / chức vụ)" },
  { word: "access", meaning: "entry: quyền truy cập / tiếp cận | have access to + N (có quyền truy cập...)" },
  { word: "accessible", meaning: "easy to reach/use: dễ tiếp cận | accessible documents/bridges (tài liệu / cầu dễ tiếp cận)" },
  { word: "accommodate", meaning: "adjust for: đáp ứng, điều chỉnh | accommodate growth / needs (đáp ứng sự tăng trưởng / nhu cầu)" },
  { word: "accomplishment", meaning: "achievement: thành tựu | list accomplishments in a cover letter (liệt kê thành tựu trong thư giới thiệu)" },
  { word: "according to", meaning: "as stated by: theo như | according to reports / surveys / contracts" },
  { word: "accordingly", meaning: "therefore: vì vậy | dùng để chỉ kết quả tất yếu" },
  { word: "account", meaning: "user profile: tài khoản | switch accounts / close an account (đổi / đóng tài khoản)" },
  { word: "accurate", meaning: "correct: chính xác | accurate records / information (hồ sơ / thông tin chính xác)" },
  { word: "accustomed", meaning: "familiar: quen với | be accustomed to + N / V-ing (quen với...)" },
  { word: "acquisition", meaning: "purchase: sự mua lại, sáp nhập | announce the acquisition of a company (công bố việc mua lại công ty)" },
  { word: "across", meaning: "throughout / on the other side: khắp / bên kia | across regions / across from the mall" },
  { word: "actively", meaning: "energetically: tích cực | actively seek qualified candidates (tích cực tìm ứng viên đủ điều kiện)" },
  { word: "addition", meaning: "extra: sự bổ sung | addition to + N (sự bổ sung cho...)" },
  { word: "additional", meaning: "extra: thêm | additional sessions / staff (buổi học / nhân sự bổ sung)" },
  { word: "additionally", meaning: "moreover: thêm vào đó | dùng để nối ý bổ sung" },
  { word: "adequate", meaning: "sufficient: đầy đủ, thích hợp | adequate space / funds (không gian / kinh phí đủ)" },
  { word: "adjacent", meaning: "next to: liền kề | adjacent buildings (các tòa nhà liền kề)" },
  { word: "adjacent to", meaning: "next to: sát cạnh | adjacent to the station (sát nhà ga)" },
  { word: "adjustment", meaning: "modification: sự điều chỉnh | adjustment to + N (điều chỉnh đối với...)" },
  { word: "advance", meaning: "beforehand: trước, trước đó | in advance of + N (trước khi...)" },
  { word: "advancement", meaning: "promotion: sự thăng tiến | focus on career advancement (tập trung vào thăng tiến sự nghiệp)" },
  { word: "advisable", meaning: "recommended: nên làm | It is advisable that + S + V (nên là...)" },
  { word: "affordable", meaning: "reasonably priced: giá cả phải chăng | affordable housing/prices (nhà ở / giá cả hợp lý)" },
  { word: "after", meaning: "following: sau | after a meeting / after work (sau cuộc họp / sau giờ làm)" },
  { word: "after that time", meaning: "later: sau thời điểm đó | dùng để nối mốc thời gian" },
  { word: "after this", meaning: "following this: sau việc này | dùng trong hướng dẫn/trình tự" },
  { word: "afterward", meaning: "later: sau đó | complete the form and submit it afterward" },
  { word: "again", meaning: "once more: lại, lần nữa | reopen again (mở lại)" },
  { word: "agree", meaning: "consent: đồng ý | agree that + S + V (đồng ý rằng...)" },
  { word: "agreement", meaning: "contract: thỏa thuận | be in agreement with + N (đồng thuận với...)" },
  { word: "ahead of", meaning: "before: trước | ahead of schedule / deadline (trước tiến độ / hạn chót)" },
  { word: "aim", meaning: "goal: mục tiêu / nhắm đến | aim is to + V (mục tiêu là...)" },
  { word: "alert (N)", meaning: "notice: thông báo | issue an alert (phát thông báo)" },
  { word: "alert (V)", meaning: "notify: thông báo cho | alert A to B (thông báo A về B)" },
  { word: "allow", meaning: "permit: cho phép | allow + O + to + V (cho phép ai làm gì)" },
  { word: "allow for", meaning: "take into account: tính đến | allow for delays (tính đến sự chậm trễ)" },
  { word: "allowance", meaning: "expense: khoản phụ cấp | travel allowance (phụ cấp đi công tác)" },
  { word: "along", meaning: "following: dọc theo | along the road / river (dọc theo con đường / con sông)" },
  { word: "along with", meaning: "together with: cùng với | documents along with receipts" },
  { word: "also", meaning: "in addition: cũng, thêm vào | dùng để bổ sung thông tin" },
  { word: "alternative", meaning: "option: phương án thay thế | alternative to + N (giải pháp thay thế cho...)" },
  { word: "always", meaning: "at all times: luôn luôn | always contact the manager khi có vấn đề" },
  { word: "ambitious", meaning: "large-scale: tham vọng, quy mô lớn | ambitious expansion plans (kế hoạch mở rộng lớn)" },
  { word: "amenity", meaning: "convenience, facility: tiện ích | use on-site amenities (sử dụng các tiện ích tại chỗ)" },
  { word: "among", meaning: "in the middle of: trong số | among + plural nouns (trong số nhiều...)" },
  { word: "amount", meaning: "quantity: số lượng | a large amount of time / money (một lượng lớn thời gian / tiền)" },
  { word: "ample", meaning: "more than enough: dư dả, đầy đủ | ample space for visitors (đủ không gian cho khách)" },
  { word: "announce", meaning: "make public: công bố | announce that + S + V / announce an event (công bố rằng... / công bố sự kiện)" },
  { word: "annual", meaning: "yearly: hằng năm | annual conference / report (hội nghị / báo cáo thường niên)" },
  { word: "anonymously", meaning: "without name: ẩn danh | submit feedback anonymously (gửi phản hồi ẩn danh)" },
  { word: "anticipate", meaning: "expect: dự đoán, lường trước | anticipate a shortage / demand (dự đoán thiếu hụt / nhu cầu)" },
  { word: "anticipated", meaning: "expected: được dự đoán | anticipated arrival time (thời gian đến dự kiến)" },
  { word: "apologetic", meaning: "expressing regret: mang tính xin lỗi | be apologetic about delays (xin lỗi về sự chậm trễ)" },
  { word: "apparently", meaning: "seemingly: dường như | apparently correct (dường như đúng)" },
  { word: "appeal", meaning: "attraction / request: sự hấp dẫn / kêu gọi | appeal to customers (thu hút khách hàng)" },
  { word: "appear", meaning: "seem: có vẻ như | appear to be + N/Adj (có vẻ là...)" },
  { word: "appliance", meaning: "household device: thiết bị gia dụng | kitchen appliances (thiết bị nhà bếp)" },
  { word: "application", meaning: "form: đơn đăng ký | submit an application (nộp đơn)" },
  { word: "appoint", meaning: "assign: bổ nhiệm | appoint A as B (bổ nhiệm A làm B)" },
  { word: "appointment", meaning: "scheduled meeting: cuộc hẹn | schedule an appointment (đặt lịch hẹn)" },
  { word: "approach (N)", meaning: "method: cách tiếp cận | a cautious approach to + N (cách tiếp cận thận trọng với...)" },
  { word: "approach (V)", meaning: "come closer: đến gần | the deadline is approaching (hạn chót đang đến gần)" },
  { word: "appropriate", meaning: "suitable: phù hợp | appropriate for + N (phù hợp với...)" },
  { word: "approval", meaning: "permission: sự chấp thuận | receive approval for purchases (nhận phê duyệt cho việc mua sắm)" },
  { word: "array", meaning: "variety: một loạt | an array of options / services (một loạt lựa chọn / dịch vụ)" },
  { word: "as", meaning: "role / comparison: như, với tư cách là | work as a manager / hired as staff" },
  { word: "as a matter of fact", meaning: "in reality: thực tế là | dùng để nhấn mạnh, bổ sung thông tin" },
  { word: "as a result", meaning: "therefore: do đó, kết quả là | dùng để chỉ kết quả trực tiếp" }
];
