// ============================================================
//  DATA.JS — Bộ từ vựng của bạn
//  Chỉnh sửa mảng này để thay đổi nội dung học.
//  Mỗi object gồm:
//    word    — từ tiếng Anh (sẽ là đáp án)
//    meaning — nghĩa tiếng Việt (sẽ hiển thị trên màn hình)
// ============================================================

const vocabularies = [
  { word: "ability", meaning: "ability ~ to do (có khả năng làm gì)" },
  { word: "able", meaning: "be able to do (có thể làm gì)" },
  { word: "about to", meaning: "be about to do (sắp sửa làm gì)" },
  { word: "above all", meaning: "trên hết, quan trọng nhất (dùng để nhấn mạnh)" },
  { word: "abruptly", meaning: "đột ngột (kết thúc/ngắt ngang bất ngờ)" },
  { word: "absence", meaning: "absence of + N (sự vắng mặt của ...)" },
  { word: "accept", meaning: "chấp nhận (đề nghị, tiền, chức vụ, giải thưởng)" },
  { word: "access", meaning: "have access to + N (có quyền truy cập/tiếp cận)" },
  { word: "accessible", meaning: "có thể tiếp cận sử dụng được (địa điểm, tài liệu)" },
  { word: "accommodate", meaning: "đáp ứng, chứa (nhu cầu, sự tăng trưởng)" },
  { word: "accomplishment", meaning: "thành tựu (thường trong thư giới thiệu)" },
  { word: "according to", meaning: "theo như (báo cáo, nghiên cứu, hợp đồng)" },
  { word: "accordingly", meaning: "vì vậy, do đó (quan hệ nhân quả)" },
  { word: "account", meaning: "tài khoản (dịch vụ, ngân hàng)" },
  { word: "accurate", meaning: "chính xác (thông tin, dữ liệu, hồ sơ)" },
  { word: "accustomed", meaning: "be accustomed to + N / V-ing (quen với)" },
  { word: "acquisition", meaning: "sự mua lại, thâu tóm (công ty)" },
  { word: "across", meaning: "trên khắp / đối diện (khu vực, phạm vi)" },
  { word: "actively", meaning: "một cách tích cực (actively seek/recruit)" },
  { word: "addition", meaning: "in addition to + N (ngoài ... ra còn)" },
  { word: "additional", meaning: "thêm, bổ sung (nhân sự, sự kiện)" },
  { word: "additionally", meaning: "hơn nữa, thêm vào đó (liên từ bổ sung)" },
  { word: "adequate", meaning: "đủ, phù hợp (adequate for needs)" },
  { word: "adjacent", meaning: "liền kề (vị trí)" },
  { word: "adjacent to", meaning: "kề bên, sát với (địa điểm)" },
  { word: "adjustment", meaning: "adjustment ~ to + N (sự điều chỉnh đối với cái gì)" },
  { word: "advance", meaning: "in advance of + N (trước, sớm hơn)" },
  { word: "advancement", meaning: "sự thăng tiến (career advancement)" },
  { word: "advisable", meaning: "It is advisable that + S + V (nên làm gì)" },
  { word: "affordable", meaning: "giá cả hợp lý, có thể chi trả" },
  { word: "after", meaning: "sau + thời gian / sự kiện" },
  { word: "after that time", meaning: "sau thời điểm đó" },
  { word: "after this", meaning: "sau việc này" },
  { word: "afterward", meaning: "sau đó, về sau" },
  { word: "again", meaning: "lại, lần nữa" },
  { word: "agree", meaning: "agree that + mệnh đề" },
  { word: "agreement", meaning: "be in agreement with + N (đồng ý với)" },
  { word: "ahead of", meaning: "trước, sớm hơn (thời gian / lịch / hạn)" },
  { word: "aim", meaning: "aim is to do (mục tiêu là làm gì)" },
  { word: "alert", meaning: "receive an alert (nhận thông báo) | alert A to B (thông báo cho A về B)" },
  { word: "allow", meaning: "allow + O + to do (cho phép làm gì)" },
  { word: "allow for", meaning: "tính đến, dự trù" },
  { word: "allowance", meaning: "travel allowance (phụ cấp, chi phí)" },
  { word: "along", meaning: "along + danh từ chỉ đường / vật dài" },
  { word: "along with", meaning: "A along with B (A cùng với B)" },
  { word: "also", meaning: "cũng, thêm vào (liên kết ý)" },
  { word: "alternative", meaning: "alternative to + N (giải pháp thay thế)" },
  { word: "always", meaning: "luôn luôn" },
  { word: "ambitious", meaning: "ambitious expansion plan (kế hoạch mở rộng lớn)" },
  { word: "amenity", meaning: "make use of amenities (sử dụng tiện ích/cơ sở tiện nghi)" },
  { word: "among", meaning: "among + plural nouns (trong số giữa ...)" },
  { word: "amount", meaning: "a(n) amount of + time/money (một lượng thời gian/tiền)" },
  { word: "ample", meaning: "ample + N (ample space/time) (đủ, dư dả) | ample space for + N (đủ chỗ cho ...)" },
  { word: "announce", meaning: "announce that + S + V (thông báo rằng...) | announce + event/retirement/merger" },
  { word: "annual", meaning: "annual + N (annual meeting/report) (hằng năm)" },
  { word: "anonymously", meaning: "submit/provide + feedback anonymously (gửi phản hồi ẩn danh)" },
  { word: "anticipate", meaning: "anticipate + N (dự đoán/lo ngại điều gì) | anticipate that + S + V (dự đoán rằng...)" },
  { word: "anticipated", meaning: "anticipated + N (được dự đoán) | 10 phút trước giờ đến dự kiến" },
  { word: "apologetic", meaning: "be apologetic about/for + N (tỏ ra xin lỗi vì ...)" },
  { word: "apparently", meaning: "hình như có vẻ như... (dùng khi nói 'xem ra đúng là...')" },
  { word: "appeal", meaning: "appeal to + N (thu hút/ hấp dẫn đối tượng nào)" },
  { word: "appear", meaning: "appear to be + N/adj (có vẻ là...) | it appears that + S + V (có vẻ như...)" },
  { word: "appliance", meaning: "home appliances (đồ gia dụng) | appliance manufacturer (nhà sản xuất thiết bị)" },
  { word: "application", meaning: "submit/file an application (nộp đơn) | application for + N (đơn xin...)" },
  { word: "appoint", meaning: "appoint A (as) B (bổ nhiệm A làm B)" },
  { word: "appointment", meaning: "schedule/make an appointment (đặt lịch hẹn)" },
  { word: "approach", meaning: "a(n) approach to + N (cách tiếp cận đối với...) | (deadline/date) is approaching" },
  { word: "appropriate", meaning: "appropriate for + N (phù hợp với ...) | appropriate to do (thích hợp để làm...)" },
  { word: "approval", meaning: "receive/get approval (được phê duyệt) | approval for + N (phê duyệt cho việc...)" },
  { word: "array", meaning: "an array of + plural nouns (một loạt/nhiều loại...)" },
  { word: "as", meaning: "as + N (với tư cách là...) | as + clause (khi/bởi vì/như)" },
  { word: "as a matter of fact", meaning: "thực ra, thực tế là (dùng để nhấn mạnh/đính chính)" },
  { word: "as a result", meaning: "as a result, + clause (kết quả là...) | as a result of + N (do kết quả của...)" }
];
